// .open-next/worker.js is generated by `npm run build:cloudflare`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore generated at build time
import { default as handler } from './.open-next/worker.js';
import { verifySessionTokenWithSecret, SESSION_COOKIE_NAME } from './lib/server-session';

function parseCookies(cookieHeader?: string | null): Record<string, string> {
  if (!cookieHeader) return {};
  return cookieHeader.split(';').reduce<Record<string, string>>((acc, part) => {
    const [name, ...value] = part.trim().split('=');
    if (!name) return acc;
    acc[name] = decodeURIComponent(value.join('='));
    return acc;
  }, {});
}

type OpenNextHandler = {
  fetch: (request: Request, env: WorkerEnv, context: WorkerExecutionContext) => Promise<Response> | Response;
};

type ScheduledControllerLike = {
  cron: string;
};

type WorkerEnv = Record<string, string | undefined>;

type WorkerExecutionContext = {
  waitUntil?: (promise: Promise<unknown>) => void;
};

const openNextHandler = handler as OpenNextHandler;

// wrangler.toml [triggers] crons 와 정확히 일치해야 한다.
// license-expiry-check 는 별도 cron 이 아니라 push-subscription-cleanup 끝에 통합 실행됨.
const CRON_ROUTES_BY_SCHEDULE: Record<string, string[]> = {
  '0 15 * * *': ['/api/cron/backup'],
  '0 17 * * *': ['/api/cron/chat-retention'],
  '0 23 * * *': ['/api/cron/chat-push-dispatch'],
  '0 3 * * *': ['/api/cron/push-subscription-cleanup'],
  '0 0 * * *': [
    '/api/cron/unread-notification-repush',
    '/api/cron/leave-notice-announcements',
    '/api/cron/birthday-announcements',
    // 연차 자동화 (KST 09:00 매일):
    '/api/cron/annual-leave-accrual',     // 1년미만 월 만근 +1 / 만N년 연차 자동부여
    '/api/cron/annual-leave-promotion',   // 1차·2차 연차사용촉진 자동 발송
    '/api/cron/annual-leave-expiry',      // 촉진 2회 완료 후 미사용 연차 자동소멸 (★기존 미등록 버그 수정)
    '/api/cron/substitute-holiday',       // 공휴일 근무 → 대체휴무 자동지급
    '/api/cron/payroll-notice'            // 급여일(payrollDay) 도래 시 HR/관리자에게 급여명세서 발송 확인 리마인더
  ],
  '0 4 * * *': ['/api/temp/resend'],      // KST 13:00 — 임시 재발송
};

async function callCronRoute(
  route: string,
  cron: string,
  env: WorkerEnv,
  context: WorkerExecutionContext,
) {
  const cronSecret = String(env.CRON_SECRET || '').trim();
  if (!cronSecret) {
    throw new Error('CRON_SECRET is not configured.');
  }

  const response = await openNextHandler.fetch(
    new Request(`https://worker-cron.local${route}`, {
      method: 'GET',
      headers: {
        authorization: `Bearer ${cronSecret}`,
        'x-cloudflare-cron': cron,
      },
    }),
    env,
    context,
  );

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(`Cron route ${route} failed with ${response.status}: ${detail}`);
  }
}

const worker = {
  // OpenNext 가 생성한 fetch 핸들러로 위임 (this 바인딩 보존을 위해 래핑 호출).
  async fetch(request: Request, env: WorkerEnv, context: WorkerExecutionContext) {
    const url = new URL(request.url);
    if (url.pathname === '/api/realtime/ws') {
      if (request.headers.get('Upgrade') !== 'websocket') {
        return new Response('Expected Upgrade: websocket', { status: 426 });
      }

      const cookies = parseCookies(request.headers.get('Cookie'));
      const token = cookies[SESSION_COOKIE_NAME];
      const secret = String(env.SESSION_SECRET || 'dev-only-session-secret-change-this').trim();

      const session = await verifySessionTokenWithSecret(token, secret);
      if (!session || !session.user || !session.user.id) {
        return new Response('Unauthorized', { status: 401 });
      }

      const userId = String(session.user.id);
      const userName = String(session.user.name || '알 수 없음');

      const hub = env.REALTIME_HUB as any;
      if (!hub) {
        return new Response('REALTIME_HUB DurableObject binding not found', { status: 500 });
      }

      const doId = hub.idFromName('pchos-realtime-v1');
      const stub = hub.get(doId);

      const newHeaders = new Headers(request.headers);
      newHeaders.set('x-realtime-user-id', userId);
      newHeaders.set('x-realtime-user-name', userName);

      const doRequest = new Request(request, {
        headers: newHeaders,
      });

      return stub.fetch(doRequest);
    }
    return openNextHandler.fetch(request, env, context);
  },

  async scheduled(
    controller: ScheduledControllerLike,
    env: WorkerEnv,
    context: WorkerExecutionContext,
  ) {
    const routes = CRON_ROUTES_BY_SCHEDULE[controller.cron] || [];
    if (routes.length === 0) return;

    console.log(
      `[cron ${controller.cron}] Starting execution of ${routes.length} routes sequentially...`,
    );

    for (const route of routes) {
      const startTime = Date.now();
      try {
        console.log(`[cron ${controller.cron}] Starting route: ${route}`);
        await callCronRoute(route, controller.cron, env, context);
        const duration = Date.now() - startTime;
        console.log(
          `[cron ${controller.cron}] Successfully finished route: ${route} (${duration}ms)`,
        );
      } catch (err) {
        const duration = Date.now() - startTime;
        console.error(
          `[cron ${controller.cron}] Route ${route} failed after ${duration}ms:`,
          err,
        );
      }
    }
    console.log(`[cron ${controller.cron}] Finished all routes.`);
  },
};

export { RealtimeHub } from './lib/realtime/realtime-hub';
export default worker;
