// .open-next/worker.js is generated by `npm run build:cloudflare`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore generated at build time
import { default as handler } from './.open-next/worker.js';

type OpenNextHandler = {
  fetch: (request: Request, env: WorkerEnv, context: WorkerExecutionContext) => Promise<Response> | Response;
};

type ScheduledControllerLike = {
  cron: string;
};

type WorkerEnv = Record<string, string | undefined>;

type WorkerExecutionContext = {
  waitUntil?: (promise: Promise<unknown>) => void;
};

const openNextHandler = handler as OpenNextHandler;

// wrangler.toml [triggers] crons 와 정확히 일치해야 한다.
// license-expiry-check 는 별도 cron 이 아니라 push-subscription-cleanup 끝에 통합 실행됨.
const CRON_ROUTES_BY_SCHEDULE: Record<string, string[]> = {
  '0 15 * * *': ['/api/cron/backup'],
  '0 17 * * *': ['/api/cron/chat-retention'],
  '0 23 * * *': ['/api/cron/chat-push-dispatch'],
  '0 3 * * *': ['/api/cron/push-subscription-cleanup'],
  '0 0 * * *': [
    '/api/cron/unread-notification-repush',
    '/api/cron/leave-notice-announcements',
    '/api/cron/birthday-announcements',
    // 연차 자동화 (KST 09:00 매일):
    '/api/cron/annual-leave-accrual',     // 1년미만 월 만근 +1 / 만N년 연차 자동부여
    '/api/cron/annual-leave-promotion',   // 1차·2차 연차사용촉진 자동 발송
    '/api/cron/annual-leave-expiry',      // 촉진 2회 완료 후 미사용 연차 자동소멸 (★기존 미등록 버그 수정)
    '/api/cron/substitute-holiday',       // 공휴일 근무 → 대체휴무 자동지급
    '/api/cron/payroll-notice'            // 급여일(payrollDay) 도래 시 HR/관리자에게 급여명세서 발송 확인 리마인더
  ],
  '0 4 * * *': ['/api/temp/resend'],      // KST 13:00 — 임시 재발송
};

async function callCronRoute(
  route: string,
  cron: string,
  env: WorkerEnv,
  context: WorkerExecutionContext,
) {
  const cronSecret = String(env.CRON_SECRET || '').trim();
  if (!cronSecret) {
    throw new Error('CRON_SECRET is not configured.');
  }

  const response = await openNextHandler.fetch(
    new Request(`https://worker-cron.local${route}`, {
      method: 'GET',
      headers: {
        authorization: `Bearer ${cronSecret}`,
        'x-cloudflare-cron': cron,
      },
    }),
    env,
    context,
  );

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(`Cron route ${route} failed with ${response.status}: ${detail}`);
  }
}

const worker = {
  // OpenNext 가 생성한 fetch 핸들러로 위임 (this 바인딩 보존을 위해 래핑 호출).
  fetch(request: Request, env: WorkerEnv, context: WorkerExecutionContext) {
    return openNextHandler.fetch(request, env, context);
  },

  async scheduled(
    controller: ScheduledControllerLike,
    env: WorkerEnv,
    context: WorkerExecutionContext,
  ) {
    const routes = CRON_ROUTES_BY_SCHEDULE[controller.cron] || [];
    if (routes.length === 0) return;

    // allSettled: 한 라우트 실패가 같은 cron 의 다른 라우트 실행을 막지 않도록 격리(JM3).
    const results = await Promise.allSettled(
      routes.map((route) => callCronRoute(route, controller.cron, env, context)),
    );
    results.forEach((result, index) => {
      if (result.status === 'rejected') {
        console.error(
          `[cron ${controller.cron}] route ${routes[index]} failed:`,
          result.reason,
        );
      }
    });
  },
};

export default worker;
