export {
  MAX_FILE_SIZE_BYTES as CHAT_MAX_FILE_SIZE_BYTES,
  MAX_VIDEO_SIZE_BYTES as CHAT_MAX_VIDEO_SIZE_BYTES,
  MAX_IMAGE_SIZE_BYTES as CHAT_MAX_IMAGE_SIZE_BYTES,
  MAX_FILE_SIZE_LABEL as CHAT_MAX_FILE_SIZE_LABEL,
  MAX_VIDEO_SIZE_LABEL as CHAT_MAX_VIDEO_SIZE_LABEL,
  MAX_IMAGE_SIZE_LABEL as CHAT_MAX_IMAGE_SIZE_LABEL,
} from '@/lib/upload-constants';
